db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=localdevpwd
    - MYSQL_DATABASE=task
    - MYSQL_USER=task
    - MYSQL_PASSWORD=taskpwd
rabbit1:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
  environment:
    - RABBITMQ_NODENAME=rabbit1
